version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postge
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
      build: ./server
      container_name: server
      environment:
        NODE_ENV: ${NODE_ENV}
        DATABASE_HOST: postge
        DATABASE_PORT: 5432
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_NAME: ${DATABASE_NAME}
        PORT: ${PORT}
        ORIGIN: ${ORIGIN}
        SECRET: ${SECRET}
        JWT_SECRET: ${JWT_SECRET}
      depends_on:
        - db
      ports:
        - "8080:8080"

  client:
    build: ./client
    container_name: client
    environment:
      REACT_APP_API_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  db_data:
